-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into boarding_type (value) values ('DEPEARTURE');
-- insert into boarding_type (value) values ('RETURN');
