-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."package" add column "isAvailable" boolean
--  not null default 'true';
